--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Hobbies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Hobbies" (
    "HobbyID" integer NOT NULL,
    "Name" character varying
);


ALTER TABLE public."Hobbies" OWNER TO postgres;

--
-- Name: Hobbies_HobbyID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Hobbies" ALTER COLUMN "HobbyID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hobbies_HobbyID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Profiles" (
    "ProfileID" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Birthdate" date,
    "NumOfPosts" integer,
    "HobbyID" integer NOT NULL,
    "Username" character varying
);


ALTER TABLE public."Profiles" OWNER TO postgres;

--
-- Name: Profiles_HobbyID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Profiles_HobbyID_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Profiles_HobbyID_seq" OWNER TO postgres;

--
-- Name: Profiles_HobbyID_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Profiles_HobbyID_seq" OWNED BY public."Profiles"."HobbyID";


--
-- Name: Profiles_ProfileID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Profiles" ALTER COLUMN "ProfileID" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Profiles_ProfileID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Profiles_UserId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Profiles_UserId_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Profiles_UserId_seq" OWNER TO postgres;

--
-- Name: Profiles_UserId_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Profiles_UserId_seq" OWNED BY public."Profiles"."UserId";


--
-- Name: TopTrends; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TopTrends" (
    "TrendID" integer NOT NULL,
    "TrendName" character varying NOT NULL
);


ALTER TABLE public."TopTrends" OWNER TO postgres;

--
-- Name: TopTrends_TrendID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TopTrends" ALTER COLUMN "TrendID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TopTrends_TrendID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserInfo" (
    "UserID" integer NOT NULL,
    "Username" character varying(255) NOT NULL,
    "Firstname" character varying(255),
    "Lastname" character varying(255),
    "Email" character varying(255),
    "Password" character varying(255)
);


ALTER TABLE public."UserInfo" OWNER TO postgres;

--
-- Name: UserInfo_UserID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserInfo" ALTER COLUMN "UserID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserInfo_UserID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Profiles UserId; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles" ALTER COLUMN "UserId" SET DEFAULT nextval('public."Profiles_UserId_seq"'::regclass);


--
-- Name: Profiles HobbyID; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles" ALTER COLUMN "HobbyID" SET DEFAULT nextval('public."Profiles_HobbyID_seq"'::regclass);


--
-- Name: Hobbies Hobbies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hobbies"
    ADD CONSTRAINT "Hobbies_pkey" PRIMARY KEY ("HobbyID");


--
-- Name: Profiles Profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles"
    ADD CONSTRAINT "Profiles_pkey" PRIMARY KEY ("ProfileID");


--
-- Name: TopTrends TopTrends_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TopTrends"
    ADD CONSTRAINT "TopTrends_pkey" PRIMARY KEY ("TrendID");


--
-- Name: UserInfo User_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfo"
    ADD CONSTRAINT "User_info_pkey" PRIMARY KEY ("UserID");


--
-- Name: Profiles Hobbyname; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles"
    ADD CONSTRAINT "Hobbyname" FOREIGN KEY ("HobbyID") REFERENCES public."Hobbies"("HobbyID");


--
-- Name: Profiles UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Profiles"
    ADD CONSTRAINT "UserId" FOREIGN KEY ("UserId") REFERENCES public."UserInfo"("UserID");


--
-- PostgreSQL database dump complete
--

